format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
	$golang\
	$nodejs\
	$ruby\
	$lua\
	$env_var\
  $custom\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
	$shell\
  $time\
	$status\
  $character"""

add_newline = true

[character]
success_symbol = '[âš­ \$](bold green)'
vicmd_symbol = '[âœ’ï¸ \$](bold yellow)'
error_symbol = '[ğš¡ \$](bold red)'

[shell]
disabled = false
fish_indicator = '[Ï•](bold blue)'
bash_indicator = '[Î²](bold blue)'
zsh_indicator = '[Î¶](bold blue)'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'

[battery]
disabled = false

[status]
disabled = false

[ruby]
symbol = 'îˆ¾ '

[rust]
symbol = 'î¨ '

[docker_context]
symbol = 'ïŒˆ '

[directory]
read_only = ' ï ½'

[memory_usage]
symbol = 'ï¡š '

[package]
symbol = 'ï£– '

[swift]
symbol = 'ï¯£ '
