add_newline = true

[character]
success_symbol = '[âŸ´ ](bold green)'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'

[shell]
disabled = false
fish_indicator = 'ïœ¹'
bash_indicator = 'ğŸ’¥'
zsh_indicator = 'ğŸ’¤âš¡ï¸'

[battery]
disabled = false

[status]
disabled = false

[ruby]
symbol = 'îˆ¾ '

[rust]
symbol = 'î¨ '

[docker_context]
symbol = 'ïŒˆ '

[directory]
read_only = ' ï ½'

[memory_usage]
symbol = 'ï¡š '

[package]
symbol = 'ï£– '

[swift]
symbol = 'ï¯£ '
